# -*- coding: utf-8 -*-
"""app

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gNeOrn0Fh4RWCR1Ivt3GcfruwcEAENUS
"""

import pickle
import numpy as np
import pandas as pd

#load pickle model
model=pickle.load(open("model.pkl","rb"))

cars = [[1,90,62,12,43,27.2,0.580,24],[8,105,100,36,0,43.3,0.239,45],[5,144,82,26,285,32,0.452,58],[8,179,72,42,130,32.7,0.719,36]]
cars_col = ['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age']
cars = pd.DataFrame(cars)
print(cars)
cars.columns = cars_col
print(cars)
predictions = model.predict(cars)
#print(predictions)
'''
if predictions==1:
    print("yes")
elif predictions==0:
  print("No")
'''
